=== SanderCokart/B5-XML/eindopdracht/personen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.sandercokart.com/personen.xsd"
           xmlns="https://www.sandercokart.com/personen.xsd"
>
    <xs:simpleType name="geslachtType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="man"/>
            <xs:enumeration value="vrouw"/>
            <xs:enumeration value="anders"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="persoonType">
        <xs:sequence>
            <xs:element type="xs:string" name="voornaam"/>
            <xs:element type="xs:string" name="achternaam"/>
            <xs:element type="geslachtType" name="geslacht"/>
            <xs:element type="xs:date" name="geboortedatum"/>
            <xs:element type="xs:double" name="lengte_in_cm"/>
            <xs:element type="xs:double" name="gewicht_in_kg"/>
            <xs:element type="xs:string" name="haarkleur"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="personen">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persoon" type="persoonType" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SanderCokart/B5-XML/eindopdracht/personen.xml
<?xml version="1.0" encoding="utf-8"?>

<p:personen xmlns:p="https://www.sandercokart.com/personen.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://www.sandercokart.com/personen.xsd personen.xsd">
    <persoon>
        <voornaam>Norval</voornaam>
        <achternaam>Prohaska</achternaam>
        <geslacht>man</geslacht>
        <geboortedatum>1998-04-25</geboortedatum>
        <lengte_in_cm>178</lengte_in_cm>
        <gewicht_in_kg>75</gewicht_in_kg>
        <haarkleur>rood</haarkleur>
    </persoon>
    <persoon>
        <voornaam>Lolita</voornaam>
        <achternaam>Schultz</achternaam>
        <geslacht>man</geslacht>
        <geboortedatum>1998-04-25</geboortedatum>
        <lengte_in_cm>178</lengte_in_cm>
        <gewicht_in_kg>75</gewicht_in_kg>
        <haarkleur>rood</haarkleur>
    </persoon>
    <persoon>
        <voornaam>Eleanore</voornaam>
        <achternaam>Krajcik</achternaam>
        <geslacht>man</geslacht>
        <geboortedatum>1998-04-25</geboortedatum>
        <lengte_in_cm>178</lengte_in_cm>
        <gewicht_in_kg>75</gewicht_in_kg>
        <haarkleur>rood</haarkleur>
    </persoon>
    <persoon>
        <voornaam>Addie</voornaam>
        <achternaam>Dicki</achternaam>
        <geslacht>man</geslacht>
        <geboortedatum>1998-04-25</geboortedatum>
        <lengte_in_cm>178</lengte_in_cm>
        <gewicht_in_kg>75</gewicht_in_kg>
        <haarkleur>rood</haarkleur>
    </persoon>
    <persoon>
        <voornaam>Alfreda</voornaam>
        <achternaam>Skiles</achternaam>
        <geslacht>man</geslacht>
        <geboortedatum>1998-04-25</geboortedatum>
        <lengte_in_cm>178</lengte_in_cm>
        <gewicht_in_kg>75</gewicht_in_kg>
        <haarkleur>rood</haarkleur>
    </persoon>
    <persoon>
        <voornaam>Lenny</voornaam>
        <achternaam>Collier</achternaam>
        <geslacht>man</geslacht>
        <geboortedatum>1998-04-25</geboortedatum>
        <lengte_in_cm>178</lengte_in_cm>
        <gewicht_in_kg>75</gewicht_in_kg>
        <haarkleur>rood</haarkleur>
    </persoon>
    <persoon>
        <voornaam>Henriette</voornaam>
        <achternaam>Lubowitz</achternaam>
        <geslacht>man</geslacht>
        <geboortedatum>1998-04-25</geboortedatum>
        <lengte_in_cm>178</lengte_in_cm>
        <gewicht_in_kg>75</gewicht_in_kg>
        <haarkleur>rood</haarkleur>
    </persoon>
    <persoon>
        <voornaam>Virgie</voornaam>
        <achternaam>Corwin</achternaam>
        <geslacht>man</geslacht>
        <geboortedatum>1998-04-25</geboortedatum>
        <lengte_in_cm>178</lengte_in_cm>
        <gewicht_in_kg>75</gewicht_in_kg>
        <haarkleur>rood</haarkleur>
    </persoon>
</p:personen>
